<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <!--        <version>3.4.4</version>-->
        <version>2.7.18</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.washintontech</groupId>
    <artifactId>exchange</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>exchange</name>
    <description>Exchange</description>
    <packaging>pom</packaging>
    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>
    <properties>
        <java.version>11</java.version>
        <os.maven.plugin.version>1.7.1</os.maven.plugin.version>
        <quickfixj.version>2.3.2</quickfixj.version>
        <chronicle.queue.version>5.27ea5</chronicle.queue.version>
        <agrona.version>1.19.2</agrona.version>
        <disruptor.version>4.0.0</disruptor.version>
        <chronicle.map.version>3.27ea0</chronicle.map.version>
        <protoc.version>3.25.3</protoc.version>
        <grpc.version>1.70.0</grpc.version>
        <protobuf.java.version>3.25.6</protobuf.java.version>
        <protobuf.maven.plugin.version>0.6.1</protobuf.maven.plugin.version>
        <tomcat.annotations.version>6.0.53</tomcat.annotations.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>org.washingtontech</groupId>
            <artifactId>exchange-broker-proto</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>net.openhft</groupId>
            <artifactId>chronicle-queue</artifactId>
            <version>${chronicle.queue.version}</version>
        </dependency>
        <dependency>
            <groupId>org.agrona</groupId>
            <artifactId>agrona</artifactId>
            <version>${agrona.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lmax</groupId>
            <artifactId>disruptor</artifactId>
            <version>${disruptor.version}</version>
        </dependency>
        <dependency>
            <groupId>net.openhft</groupId>
            <artifactId>chronicle-map</artifactId>
            <version>${chronicle.map.version}</version>
        </dependency>
        <!-- QuickFIX/J Core -->
        <dependency>
            <groupId>org.quickfixj</groupId>
            <artifactId>quickfixj-core</artifactId>
            <version>${quickfixj.version}</version>
        </dependency>
        <!-- QuickFIX/J Generated FIX44 Messages -->
        <dependency>
            <groupId>org.quickfixj</groupId>
            <artifactId>quickfixj-messages-fix44</artifactId>
            <version>${quickfixj.version}</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty-shaded</artifactId>
            <version>${grpc.version}</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-protobuf</artifactId>
            <version>${grpc.version}</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-stub</artifactId>
            <version>${grpc.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>annotations-api</artifactId>
            <version>${tomcat.annotations.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <version>3.0.2</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.38</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.17.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <modules>
        <module>common</module>
        <module>audit</module>
        <module>cache</module>
        <module>output-gateway</module>
        <module>matching-engine</module>
        <module>input-gateway</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.38</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <!--            <plugin>-->
            <!--                <groupId>org.springframework.boot</groupId>-->
            <!--                <artifactId>spring-boot-maven-plugin</artifactId>-->
            <!--                <configuration>-->
            <!--                    <jvmArguments>-->
            <!--                        &lt;!&ndash;                        &#45;&#45;add-opens java.base/java.lang.reflect=ALL-UNNAMED&ndash;&gt;-->
            <!--                        &lt;!&ndash;                        &#45;&#45;add-opens java.base/java.nio=ALL-UNNAMED&ndash;&gt;-->
            <!--                        &lt;!&ndash;                        &#45;&#45;add-opens java.base/sun.nio.ch=ALL-UNNAMED&ndash;&gt;-->
            <!--                        &lt;!&ndash;                        &#45;&#45;add-opens java.base/java.io=ALL-UNNAMED&ndash;&gt;-->


            <!--                        &lt;!&ndash;                        &#45;&#45;add-exports=java.base/jdk.internal.ref=ALL-UNNAMED&ndash;&gt;-->
            <!--                        &lt;!&ndash;                        &#45;&#45;add-exports=java.base/sun.nio.ch=ALL-UNNAMED&ndash;&gt;-->
            <!--                        &lt;!&ndash;                        &#45;&#45;add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED&ndash;&gt;-->
            <!--                        &lt;!&ndash;                        &#45;&#45;add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED&ndash;&gt;-->
            <!--                        &#45;&#45;add-opens=jdk.compiler/com.sun.tools.javac=ALL-UNNAMED-->
            <!--                        &#45;&#45;add-opens=java.base/java.lang=ALL-UNNAMED-->
            <!--                        &#45;&#45;add-opens=java.base/java.lang.reflect=ALL-UNNAMED-->
            <!--                        &#45;&#45;add-opens=java.base/java.io=ALL-UNNAMED-->
            <!--                        &#45;&#45;add-opens=java.base/java.util=ALL-UNNAMED-->

            <!--                    </jvmArguments>-->
            <!--                </configuration>-->
            <!--            </plugin>-->


            <!--            <plugin>-->
            <!--                <groupId>org.springframework.boot</groupId>-->
            <!--                <artifactId>spring-boot-maven-plugin</artifactId>-->
            <!--                <configuration>-->
            <!--                    <excludes>-->
            <!--                        <exclude>-->
            <!--                            <groupId>org.project-lombok</groupId>-->
            <!--                            <artifactId>lombok</artifactId>-->
            <!--                        </exclude>-->
            <!--                    </excludes>-->
            <!--                </configuration>-->
            <!--            </plugin>-->
        </plugins>
    </build>

</project>
