<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.washintontech</groupId>
        <artifactId>exchange</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>./../pom.xml</relativePath>
    </parent>
    <artifactId>matching-engine</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>
    <properties>
    </properties>
    <dependencies>
        <!--        <dependency>-->
        <!--            <groupId>com.washintontech</groupId>-->
        <!--            <artifactId>common</artifactId>-->
        <!--            <version>${project.parent.version}</version>-->
        <!--        </dependency>-->
        <dependency>
            <groupId>com.washintontech</groupId>
            <artifactId>audit</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <dependency>
            <groupId>com.washintontech</groupId>
            <artifactId>output-gateway</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <dependency>
            <groupId>com.washintontech</groupId>
            <artifactId>cache</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.jctools/jctools-core -->
        <dependency>
            <groupId>org.jctools</groupId>
            <artifactId>jctools-core</artifactId>
            <version>4.0.5</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!--            <plugin>-->
            <!--                <groupId>org.springframework.boot</groupId>-->
            <!--                <artifactId>spring-boot-maven-plugin</artifactId>-->
            <!--            </plugin>-->
        </plugins>
    </build>

</project>
